# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

score_components_nn_nt_cpp <- function(X_nt, T_tl, wNN, eps = 1e-12) {
    .Call(`_fmriphysio_score_components_nn_nt_cpp`, X_nt, T_tl, wNN, eps)
}

